apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: gcr.io/test-installations-222013/polkassembly-front-end:master
        env:
        - name: REACT_APP_AUTH_SERVER_GRAPHQL_URL
          value: "http://auth-server-service:8010/auth/graphql"
        - name: REACT_APP_ENV
          value: "dev"
        - name: REACT_APP_HASURA_GRAPHQL_URL
          value: "http://hasura-service:8080/v1/graphql"
        - name: REACT_APP_JWT_PUBLIC_KEY
          value: "-----BEGIN PUBLIC KEY-----\nMIIBI...wIDAQAB\n-----END PUBLIC KEY-----"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
