apiVersion: v1
kind: Secret
metadata:
  name: graphql-jwt-secret
  namespace: polkassembly
type: Opaque
data:
  graphql-jwt-secret: "eyAidHlwZSI6ICJSUzI1NiIsICJrZXkiOiAiLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJ
  QklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2WG4xZnpCQkFZTmZJZFBv
  UlplcgowNFhObjQyUXBWWUJlU3Njc1FsSFNhaHFuUWNlNEJxUHFLRDdNS01CeTBBdy9FUWlvK2Vp
  UWtEMm5XaGkwZGFLCjJ1SjdiUW5BYUFuMTQ0dkZRRUlGRnpLeFIxMFdsaUpjZUVwb0w1SW9BMlg2
  amRoRjVmdkNxQUxVUmc1aTRZOUEKYVJxdW9VU2tvMHBJa1NIaGYyRGJEY0FDVm9TREdNbGtHQVU5
  YlJYa3daM0xwcW90NnIyOGc5VS9UOTI5elZwdQorVDAweXlJY3RUNUpKYWxiRDBZVG5Va09MYTJX
  QnhtbXFJRXUzeFBJVng5YTh6RzFLL294ZGpTMHJvR2M4QWkrCmlDV3A3V3FXazg4ZklOaXRONnY3
  TWZwNCtJVEN3RVhITEg0OFFqLytZWFRGUFFTZzZsVm1tclBmWDYxRjZyR1gKd1FJREFRQUIKLS0t
  LS1FTkQgUFVCTElDIEtFWS0tLS0tIiB9"
